# Generated by Django 4.0.4 on 2022-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='max_followers',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='instaaccounts',
            name='phrase',
            field=models.CharField(default='', max_length=200),
        ),
    ]
