# Generated by Django 4.0.4 on 2022-05-17 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MAIN', '0002_instaaccounts_max_followers_instaaccounts_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='attached_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insta', to=settings.AUTH_USER_MODEL),
        ),
    ]
