# Generated by Django 4.0.4 on 2022-05-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_alter_instaaccounts_attached_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ended', models.BooleanField(default=False)),
                ('stage', models.IntegerField(default=0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='MAIN.instaaccounts')),
            ],
        ),
    ]
