# Generated by Django 4.0.4 on 2022-05-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_processlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.TextField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='MAIN.process')),
            ],
        ),
    ]
