# Generated by Django 4.0.4 on 2022-05-18 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0008_violator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.TextField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='MAIN.process')),
            ],
        ),
    ]
