# Generated by Django 4.0.4 on 2022-05-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0009_mediabank'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='last_security_code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
