# Generated by Django 4.0.4 on 2022-05-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0010_instaaccounts_last_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaaccounts',
            name='last_security_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
