# Generated by Django 4.0.4 on 2022-05-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0011_alter_instaaccounts_last_security_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='hast_two_fa',
            field=models.BooleanField(default=False),
        ),
    ]
